/* eslint-disable no-undef */
buildingPlans = {
	miniharvester: [{
			//Level 1 (max 300)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		}
	],
	longDistanceBuilder: [{
			//Level 1 (max 300)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 550,
			body: [MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 550,
			body: [MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1100,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1100,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 1100,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 1100,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 1100,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY]
		}
	],

	longDistanceHarvester: [{
			//Level 1 (max 300)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 500,
			body: [MOVE, MOVE, MOVE, MOVE, WORK, WORK, CARRY, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 750,
			body: [MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1100,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1650,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 2050,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 2050,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 2050,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		}
	],

	harvester: [{
			//Level 1 (max 300)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 700,
			body: [MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1250,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1550,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 1550,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 1550,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 1550,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		}
	],

	miner: [{
			//Level 1 (max 300)
			minEnergy: 300,
			body: [MOVE, WORK, WORK, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 550,
			body: [MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 750,
			body: [MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 850,
			body: [MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 850,
			body: [MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 850,
			body: [MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 850,
			body: [MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 850,
			body: [MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY]
		}
	],

	upgrader: [{
			//Level 1 (max 300)
			minEnergy: 300,
			body: [MOVE, WORK, WORK, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 500,
			body: [MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 800,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1300,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1750,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 2200,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 3900,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 2650,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		}
	],

	repairer: [{
			//Level 1 (max 300)
			minEnergy: 200,
			body: [MOVE, WORK, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 550,
			body: [MOVE, MOVE, MOVE, WORK, WORK, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 800,
			body: [MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1150,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1550,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 1900,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 1900,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 1900,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		}
	],

	builder: [{
			//Level 1 (max 300)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 550,
			body: [MOVE, MOVE, MOVE, WORK, WORK, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 650,
			body: [MOVE, MOVE, MOVE, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1000,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1000,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 1000,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 1000,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 1000,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY]
		}
	],

	wallRepairer: [{
			//Level 1 (max 300)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 550,
			body: [MOVE, MOVE, MOVE, WORK, WORK, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 800,
			body: [MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1150,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1550,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 1900,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 1900,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 1900,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		}
	],

	claimer: [{
			//Level 1 (max 300)
			minEnergy: 650,
			body: [CLAIM, MOVE]
		},
		{
			//Level 2 (max 550)
			minEnergy: 650,
			body: [CLAIM, MOVE]
		},
		{
			//Level 3 (max 800)
			minEnergy: 650,
			body: [CLAIM, MOVE]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1300,
			body: [CLAIM, CLAIM, MOVE, MOVE]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1300,
			body: [CLAIM, CLAIM, MOVE, MOVE]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 1300,
			body: [CLAIM, CLAIM, MOVE, MOVE]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 2600,
			body: [MOVE, MOVE, MOVE, MOVE, CLAIM, CLAIM, CLAIM, CLAIM]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 2600,
			body: [MOVE, MOVE, MOVE, MOVE, CLAIM, CLAIM, CLAIM, CLAIM]
		}
	],

	bigClaimer: [{
			//Level 1 (max 300)
			minEnergy: 3250,
			body: [CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 2 (max 550)
			minEnergy: 3250,
			body: [CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 3 (max 800)
			minEnergy: 3250,
			body: [CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 3250,
			body: [CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 3250,
			body: [CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 3250,
			body: [CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 6500,
			body: [CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 9750,
			body: [CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, CLAIM, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE]
		}
	],

	guard: [{
			//Level 1 (max 300)
			minEnergy: 260,
			body: [MOVE, MOVE, ATTACK, ATTACK]
		},
		{
			//Level 2 (max 550)
			minEnergy: 520,
			body: [MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK]
		},
		{
			//Level 3 (max 800)
			minEnergy: 780,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1080,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, HEAL]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1380,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, HEAL, HEAL]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 1950,
			body: [TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, RANGED_ATTACK, RANGED_ATTACK, HEAL, HEAL]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 1950,
			body: [TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, RANGED_ATTACK, RANGED_ATTACK, HEAL, HEAL]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 1950,
			body: [TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, RANGED_ATTACK, RANGED_ATTACK, HEAL, HEAL]
		}
	],

	mineralHarvester: [{
			//Level 1 (max 300)
			minEnergy: 2000,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 2000,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 2000,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 2000,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 2000,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 2000,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 3300,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 3300,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		}
	],

	runner: [{
			//Level 1 (max 300)
			minEnergy: 300,
			body: [MOVE, MOVE, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 450,
			body: [MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 750,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1200,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1800,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 2250,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 2500,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 2500,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		}
	],

	scientist: [{
			//Level 1 (max 300)
			minEnergy: 300,
			body: [MOVE, MOVE, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 450,
			body: [MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 800,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 800,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 800,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 800,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 800,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 800,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		}
	],

	demolisher: [{
			//Level 1 (max 300)
			minEnergy: 250,
			body: [MOVE, MOVE, WORK, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 500,
			body: [MOVE, MOVE, MOVE, MOVE, WORK, WORK, CARRY, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 650,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1150,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1400,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 1850,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 2700,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 2700,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		}
	],

	longDistanceMiner: [{
			//Level 1 (max 300)
			minEnergy: 300,
			body: [WORK, WORK, CARRY, MOVE]
		},
		{
			//Level 2 (max 550)
			minEnergy: 550,
			body: [WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE]
		},
		{
			//Level 3 (max 800)
			minEnergy: 700,
			body: [WORK, WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 950,
			body: [MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 950,
			body: [MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 950,
			body: [MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 950,
			body: [MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 950,
			body: [MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY]
		}
	],

	SKHarvester: [{
			//Level 1 (max 300)
			minEnergy: 300,
			body: [WORK, WORK, CARRY, MOVE]
		},
		{
			//Level 2 (max 550)
			minEnergy: 550,
			body: [WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE]
		},
		{
			//Level 3 (max 800)
			minEnergy: 700,
			body: [WORK, WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1200,
			body: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1550,
			body: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 1550,
			body: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 1550,
			body: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 1550,
			body: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE]
		}
	],

	longDistanceLorry: [{
			//Level 1 (max 300)
			minEnergy: 300,
			body: [MOVE, MOVE, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 450,
			body: [MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 750,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1200,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1800,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 2250,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 2500,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 2500,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		}
	],

	transporter: [{
			//Level 1 (max 300)
			minEnergy: 300,
			body: [MOVE, MOVE, MOVE, CARRY, CARRY, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 500,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 600,
			body: [MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 600,
			body: [MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1800,
			body: [MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 2100,
			body: [MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 2550,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 2550,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		}
	],

	SKHauler: [{
			//Level 1 (max 300)
			minEnergy: 300,
			body: [WORK, CARRY, CARRY, MOVE, MOVE]
		},
		{
			//Level 2 (max 550)
			minEnergy: 500,
			body: [WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE]
		},
		{
			//Level 3 (max 800)
			minEnergy: 650,
			body: [WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1100,
			body: [WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 1750,
			body: [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 1750,
			body: [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 1750,
			body: [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 1750,
			body: [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE]
		}
	],

	attacker: [{
			//Level 1 (max 300)
			minEnergy: 260,
			body: [MOVE, MOVE, ATTACK, ATTACK]
		},
		{
			//Level 2 (max 550)
			minEnergy: 390,
			body: [MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK]
		},
		{
			//Level 3 (max 800)
			minEnergy: 800,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1300,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK]
		},
		{
			//Level 5 (max 1750)
			minEnergy: 1350,
			body: [TOUGH, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, MOVE]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 2270,
			body: [TOUGH, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, MOVE]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 3040,
			body: [TOUGH, TOUGH, TOUGH, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, MOVE, ATTACK, MOVE, MOVE, MOVE]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 3040,
			body: [TOUGH, TOUGH, TOUGH, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, MOVE, ATTACK, MOVE, MOVE, MOVE]
		}
	],

	archer: [{
			//Level 1 (max 300)
			minEnergy: 260,
			body: [MOVE, MOVE, RANGED_ATTACK, RANGED_ATTACK]
		},
		{
			//Level 2 (max 550)
			minEnergy: 390,
			body: [MOVE, MOVE, MOVE, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK]
		},
		{
			//Level 3 (max 800)
			minEnergy: 800,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1300,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK]
		},
		{
			//Level 5 (max 1750)
			minEnergy: 1350,
			body: [TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 2270,
			body: [TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 3040,
			body: [TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 3040,
			body: [TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK]
		}
	],

	healer: [{
			//Level 1 (max 300)
			minEnergy: 300,
			body: [MOVE, HEAL]
		},
		{
			//Level 2 (max 550)
			minEnergy: 300,
			body: [MOVE, HEAL]
		},
		{
			//Level 3 (max 800)
			minEnergy: 600,
			body: [MOVE, MOVE, HEAL, HEAL]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1300,
			body: [MOVE, MOVE, MOVE, MOVE, HEAL, HEAL, HEAL, HEAL]
		},
		{
			//Level 5 (max 1750)
			minEnergy: 1500,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, HEAL, HEAL, HEAL, HEAL, HEAL]
		},
		{
			//Level 6 (max 2100)
			minEnergy: 2270,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 5400,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 7500,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL]
		}
	],



	einarr: [{
			//Level 1 (max 300)
			minEnergy: 260,
			body: [MOVE, MOVE, ATTACK, ATTACK]
		},
		{
			//Level 2 (max 550)
			minEnergy: 490,
			body: [TOUGH, MOVE, MOVE, MOVE, ATTACK, HEAL]
		},
		{
			//Level 3 (max 800)
			minEnergy: 790,
			body: [TOUGH, MOVE, MOVE, MOVE, MOVE, ATTACK, HEAL, HEAL]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1290,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, HEAL, HEAL, HEAL]
		},
		{
			//Level 5 (max 1750)
			minEnergy: 1480,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, HEAL, HEAL, HEAL]
		},
		{
			//Level 6 (max 2100)
			minEnergy: 1910,
			body: [TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, HEAL, HEAL, HEAL, HEAL]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 5220,
			body: [TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 5220,
			body: [TOUGH, HEAL, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, HEAL, MOVE, HEAL, MOVE, HEAL, MOVE, HEAL, MOVE, HEAL, MOVE, HEAL, MOVE, HEAL, MOVE, HEAL, MOVE, HEAL, MOVE, HEAL, MOVE, HEAL, MOVE, MOVE]
		}
	],
	herocreep: [{
			//Level 1 (max 300)
			minEnergy: 1250,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 2 (max 550)
			minEnergy: 1250,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 3 (max 800)
			minEnergy: 1250,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 1250,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 5 (max 1750)
			minEnergy: 1250,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 6 (max 2100)
			minEnergy: 1250,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 1250,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 1250,
			body: [MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY]
		}
	],

	scout: [{
			//Level 1 (max 300)
			minEnergy: 60,
			body: [TOUGH, MOVE]
		},
		{
			//Level 2 (max 550)
			minEnergy: 60,
			body: [TOUGH, MOVE]
		},
		{
			//Level 3 (max 800)
			minEnergy: 60,
			body: [TOUGH, MOVE]
		},
		{
			//Level 4 (max 1300)
			minEnergy: 160,
			body: [TOUGH, MOVE, MOVE, CARRY]
		},
		{
			//Level 5 (max 1800)
			minEnergy: 160,
			body: [TOUGH, MOVE, MOVE, CARRY]
		},
		{
			//Level 6 (max 2300)
			minEnergy: 160,
			body: [TOUGH, MOVE, MOVE, CARRY]
		},
		{
			//Level 7 (max 5600)
			minEnergy: 160,
			body: [TOUGH, MOVE, MOVE, CARRY]
		},
		{
			//Level 8 (max 12900)
			minEnergy: 160,
			body: [TOUGH, MOVE, MOVE, CARRY]
		}
	]
};